### ISSUE TITLE
Low-res recon bug

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#123]
Jordan, I was working on trying to do a preliminary multi-grid implementation, and I think I found a bug. I set up a separate branch for the bug-fix. The branch is called "low_res_bug_fix". If your run the script ``demo/demo_multires.py``, it will crash. But if you change the parameter 

> ``delta_pixel = 4.0``
to
> ``delta_pixel = 2.0``

Then it works fine. There seems to be a problem when delta_pixel is greater than 4.

**Comment by sjkisner** [comment]
@cabouman I don't get the error on my linux machine but I do on my mac with clang.

What OS and compiler are you using?

**Comment by cabouman** [comment]
I'm using clang, so I guess it must be a compiler specific bug. Not good.

**Comment by sjkisner** [comment]
This doesn't excuse the malloc error, but in the demo when you increase the pixel size, you also want to reduce the image size in the recon arguments like,
```
num_rows=int(num_rows/delta_pixel)
num_cols=int(num_cols/delta_pixel)
```
It doesn't crash if I make that change.  

Aside: Here's another place we need to check the input values. Something like adjusting the image size if
`delta_pixel*max(num_rows+2,num_cols+2)*sqrt(2) > delta_channel*(num_channels+2*channel_offset)`

**Comment by cabouman** [comment]
For debugging purposes, I left the script that generates the malloc error in "demo_multires.py" in the branch named "low_res_bug_fix".

**Comment by sjkisner** [comment]
I believe the malloc errors were due to memory running out on our macs rather than a clang issue.
The conditions that caused this were the large image extent relative to the detectors, so it goes away with limiting image size or by reducing the roi_recon to the scan FOV.
I'll need to block out some time to analyze this. The memory is spiking in the piecewise transformation of the A matrix.

**Comment by sjkisner** [comment]
This should be fixed now.  There's been changes to the A matrix encoding, so when installing the recent change to the master branch
1) Clear out any old cached system matrix files, typically in $HOME/.cache/svmbir/parbeam/sysmatrix
2) If pulling the update to an existing local repository, run "git submodule update" before recompiling/ installing
