### ISSUE TITLE
Update submodule to point to HPI

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#132]
Jordan, we should change the submodule to point directly to HPI's sv-mbirct C repository.

Thanks Soumendu for providing the temporary development fork!

**Comment by sjkisner** [comment]
Change is in the recent pull request #133.
If pulling this update to an existing local repository, run the following to update the local files:
1) git submodule sync
2) git submodule update

**Comment by cabouman** [comment]
Done by Jordan
