### ISSUE TITLE
psutil version -- cpu_count()

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#142]
I just found the version of psutil (5.7.2) that installs with anaconda using the environment.yml file doesn't report the correct number of physical CPU cores on my linux machine (I have 20, but it reports 10). It's currently the latest version of psutil that's available through anaconda.
```
>>> import psutil
>>> psutil.cpu_count(logical=False)
10
```
If I uninstall the psutil package, and re-install using the latest version from pypi (5.8.0). It reports the correct number. 

This may be a short term issue, but it will give a huge hit to the performance using the default settings.

**Comment by cabouman** [comment]
Jordan, I wasn't able to get psutil=5.8.0 to install from conda. Otherwise, I think we could just modify the environment.yml file to be "psutil>=5.8.0".

Am I doing something wrong?

**Comment by sjkisner** [comment]
Somehow for me conda isn't showing versions available later than 5.7.2, for example from `conda search psutil` or `conda update psutil`.  If I put psutil>=5.8.0 in environment.yml I get a package not found error.  I can install psutil 5.8 using pip, but not conda. Maybe I'm missing something..

**Comment by sjkisner** [comment]
A solution is to move psutil to a pip install inside environment.yml like this:
```
name: svmbir
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - ruamel.yaml
  - pytest
  - scikit-image
  - Cython
  - pip
  - pip:
    - psutil
```

**Comment by sjkisner** [comment]
resolved
