### ISSUE TITLE
environment.yml that calls pip requirements.txt breaks cython in linux

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#146]
The conda environment created by the recent update of environment.yml (that moves everything to pip requirements) breaks the cython interface in linux.  The cython interface seems to install OK, but at runtime I get "undefined symbols" errors in the .so file.  This happens both when I build with CC=gcc and CC=icc.  It only happens for me in linux--mac/clang and mac/icc don't give me a problem.

When I create an environment with the older environment.yml the problem goes away.  The package list created in the older environment is quite a bit longer and it's not obvious to me which is the critical piece that's missing (or the wrong version). 

edit: Solved..the problem was with the package scikit-image. No problem if it's installed through conda, but something critical is missing if installing it through pip.

**Comment by sjkisner** [comment]
Is there any drawback to putting specific version numbers on all the dependencies? 
The case for it is the 2 instances recently where the version of the dependency caused the code to break.

**Comment by smajee** [comment]
@sjkisner : Can you see if this is fixed now in the new version?

**Comment by sjkisner** [comment]
Yes the current environment.yml and requirements.txt work for me.
