### ISSUE TITLE
Tomobank example - divergent behavior 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [cabouman/svmbir#154]
I have been trying to get the code to run on tomobank example #1 (https://tomobank.readthedocs.io/en/latest/source/data/docs.data.roundrobin.html) 

However, the svmbir code is resulting in a divergent behavior - the values start to blow up. I have tried the automatic parameter setting and manual ones and observed a similar outcome. 

Could one of you verify if this is indeed the case ? It might be a good example to add to the repo in any case since this is a fairly standard test real world data set.

**Comment by DamonLee5** [comment]
Hi Venkat,

I downloaded tomo_00001. There tomo_00001.h5 and tomo_00001.txt in the folder.
I think I can test it.
Do you have any code that can help me to start working with this dataset?
For example, h5 reading tool you use.

**Comment by smajee** [comment]
Tomobank offers scripts for reading in the data into numpy arrays given here: https://tomobank.readthedocs.io/en/latest/

Hope this helps.

Best,
Soumendu

On Feb 5, 2021, at 10:44 AM, Wenrui Li <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Venkat,

I downloaded tomo_00001. There tomo_00001.h5 and tomo_00001.txt in the folder.
I think I can test it.
Do you have any code that can help me to start working with this dataset?
For example, h5 reading tool you use.

**Comment by sjkisner** [comment]
Maybe I'm missing something but I can't download that tomobank file from globus.org.

**Comment by sjkisner** [comment]
I think I found the reason for this problem. Cython wasn't passing the angles array to the C functions properly.

A fix is implemented in the recent pull request. We should test the tomobank data set again.

**Comment by sjkisner** [comment]
Also, this error screws up the system matrix calculation, so matrix files need to be deleted.

**Comment by sjkisner** [comment]
Tomobank 001 looks good now so this one's resolved.
