### ISSUE TITLE
A Matrix Parallelization

### ISSUE THREAD

**Issue by XiaoWang-Github** [cabouman/svmbir#156]
Hi Jordan,

   I saw that you modified the A matrix code for parallel computations. Well done!
    The A_piecewise can also be parallelized. It should be an embarrassingly parallel function and no interaction among threads are needed.
   I estimate that the A matrix code computation speed can double.

**Comment by sjkisner** [comment]
@XiaoWang-Github  Yes, I'm working on that as we speak.  For moderate size CT problem, just parallelizing the section before the transpose gave me a 6x speedup overall with 20 threads.

**Comment by sjkisner** [comment]
Matrix parallelization is implemented now
