### ISSUE TITLE
Gordon Bell citation

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#158]
We should cite in a prominent place on the README and readthedocs that Xiao's paper for the engine was a Gordon Bell finalist.  @XiaoWang-Github is there a preferred way to reference that?

**Comment by XiaoWang-Github** [comment]
How about 

Xiao Wang, Amit Sabne, Putt Sakdhnagool, Sherman J Kisner, Charles A Bouman, and Samuel P Midkiff. Massively parallel 3d image reconstruction. In Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis, SC ‘17. 2017. doi:10.1145/3126908.3126911.​ (**Selected as a finalist for 2017 ACM Gordon Bell Prize**)

I am open to suggestions. What do you think?
