### ISSUE TITLE
package versioning

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#159]
As we transition from the "wild west" approach, as Charlie puts it, we need to establish a protocol for versioning the package.  We should especially do this before putting this up on pypi.  

This is a useful reference contributors should read:
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by cabouman** [comment]
Yes, we should make this a discussion point of our next code review.
Pretty soon, we should release version 0.2.0 .

**Comment by sjkisner** [comment]
I created a "release" branch. I suggest we use this branch to accumulate incremental changes so that we don't have to create new releases on the master branch so often. These are what I see we need to do for every new release:

1) Unit tests on "release" branch on all available platforms/compilers
2) Increment version no. in setup.py
3) Merge release into master
4) Create new release tag
5) Rebuild documentation (automatic?)
6) Build/upload release to PyPI

Anything I'm missing?

**Comment by cabouman** [comment]
Jordan, 
this is a great idea!!
So let's work on getting the updates rolled into and tested on the release branch.
Then we will push it to the master branch.

Maybe we can put your list of tasks on under the developer section of the readthedocs page.
That way we can refer to it whenever we do a new release.
Charlie

**Comment by sjkisner** [comment]
I've pushed commits directly into "release" but we should probably do pull requests for that branch.

The basic idea I'm proposing is to use this branch the way we previously were using the master branch, and we can periodically merge it into master so we don't have to go through the rigmarole of creating a new release for every code change.

**Comment by cabouman** [comment]
I love this idea. Let's do pull requests to the release branch from now on.
We also should try to do some updates of the documentation on the release branch. But it might be more difficult to test that.

**Comment by sjkisner** [comment]
@cabouman Wenrui made [instructions](https://svmbir.readthedocs.io/en/latest/docs.html) for building the html files locally so you can see what sphinx will produce without having to commit the changes.

**Comment by sjkisner** [comment]
Following suggestions I changed the new branch name to "prerelease".

**Comment by sjkisner** [comment]
We have a working protocol for maintaining package versions now. It's described in the Developers section on the [readthedocs](https://svmbir.readthedocs.io) page
