### ISSUE TITLE
physical dimension parameters

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#16]
Currently the wrapper fixes the detector and image pixel sizes to unit value.  It should allow those to be set to the actual physical dimensions otherwise you lose the physical units in the output values.

What about allowing the following arguments:
delta_channel   [default to 1, whatever units of this value here correspond to output (eg. mm -> mm^-1)]
img_downsamp  [ value>=1, default to 1,  maybe call this "delta_xy_relative"]
img_size_x_rel   [ value in (0,1], default to 1, this is approx size of image along x relative to detector width]
img_size_y_rel    [similar]

Then the image and pixel sizes would be calculated:
delta_xy = delta_channel * delta_xy_relative
Nx = ceil( img_size_x_rel * num_channels / delta_xy_relative )
Ny = ceil( img_size_y_rel * num_channels / delta_xy_relative )

**Comment by cabouman** [comment]
I like this idea.

Based on this idea, I just started a new issue to discuss how we do automated parameter selection.

**Comment by cabouman** [comment]
If we introduce arbitrary pixel pitch, then we need to make sure we don't break the svmbir.project function.

Right now svmbir.project determines the sinogram array size from the image size, but this won't always be possible if we make the pixel pitch, Nx, and Ny arbitrary.

**Comment by cabouman** [comment]
Issue fixed by new interface
