### ISSUE TITLE
Readthedocs displays misleading path for cache directory

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#172]
The documentation page (https://svmbir.readthedocs.io/en/latest/svmbir.html) displays the default cache path '/home/docs/.cache/svmbir/parbeam' in the function definition. However, the parameter description states ~/.cache/svmbir/parbeam as the default cache path.
This can be confusing to people.

I think the docs environment interprets  ~/.cache/svmbir/parbeam as /home/docs/.cache/svmbir/parbeam and displays that.
Not sure how to make it consistent.

**Comment by bwohlberg** [comment]
Your best option for dealing with this is to override the automatically generated function signature, as in [this discussion](https://stackoverflow.com/questions/12082570/override-function-declaration-in-autodoc-for-sphinx).

**Comment by sjkisner** [comment]
I fixed this [here](https://github.com/cabouman/svmbir/commit/6b04b2c87603187a0ebccc4d316828fe128a0f92) using Brendt's link.  Just had to make the function signature as part of the docstring.  I built the html locally and it worked for me.

**Comment by smajee** [comment]
One disadvantage of this approach seems to be that the function signature needs to be duplicated. But I guess it should be fine since we have more-or-less frozen the interface.

Another possible way to deal with this could be to make the default value of svmbir_lib_path None, and set it to __svmbir_lib_path if it is None.

**Comment by sjkisner** [comment]
@smajee Yeah that was something I didn't particularly like. If you change any of the defaults you have to change in the docstring too.  But it's also the case we have to change the defaults in the argument descriptions further down anyway.

I think it's worthwhile having the default path show up in the documentation to make it easier for users to know where it is.  If we use None I think you'd have to look at the code to see how it's set.

**Comment by sjkisner** [comment]
Fixed in the latest documentation
