### ISSUE TITLE
Installation from PyPI wheel error on MacOS

### ISSUE THREAD

**Issue by dyang37** [cabouman/svmbir#182]
Venkat originally brought this issue to our attention, and I am able to reproduce the same problem on my machine running macOS Big Sur + python 3.8 + gcc 10 (home-brew version).

After installing from PyPI with `pip install svmbir`, the following error occurred when importing svmbir:
```
>>> import svmbir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dyangsteven/.conda/envs/svmbir/lib/python3.8/site-packages/svmbir/__init__.py", line 1, in <module>
    from .svmbir import *
  File "/Users/dyangsteven/.conda/envs/svmbir/lib/python3.8/site-packages/svmbir/svmbir.py", line 15, in <module>
    import svmbir.interface_cy_c as ci
ImportError: dlopen(/Users/dyangsteven/.conda/envs/svmbir/lib/python3.8/site-packages/svmbir/interface_cy_c.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
  Referenced from: /Users/dyangsteven/.conda/envs/svmbir/lib/python3.8/site-packages/svmbir/interface_cy_c.cpython-38-darwin.so
  Reason: image not found
```

The direct cause of reason is because python is looking for `ibgomp.1.dylib` at path `/usr/local/opt/gcc/lib/gcc/10/`, while this directory does not exist on my machine even after I installed gcc version 10. The same `.dylib` file exists on my machine at directory `/usr/local/opt/gcc/lib/gcc/11` instead.

On the other hand, I downgraded gcc from version 11 to 10 using home-brew, and checked gcc version on my machine. It indeed gave me version 10:
```
(svmbir) pal-nat186-186-10:gcc dyangsteven$ gcc --version
gcc (Homebrew GCC 10.3.0) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This problem seems to be specific to PyPI installation using wheel. Installing from source by either doing `CC=gcc pip install .` or `pip install --no-binary svmbir svmbir` still works fine.

**Comment by dyang37** [comment]
Making a new directory `/usr/local/opt/gcc/lib/gcc/10` and copying `libgomp.1.dylib` fixed the import error. 
However we still need a more elegant solution that identifies the root cause of this issue.

**Comment by dyang37** [comment]
https://github.com/microsoft/LightGBM/issues/1369

**Comment by DamonLee5** [comment]
A possible solution is that we can put dylib to PyPI wheel. Here is the webpage to explain how to do this.
[https://stackoverflow.com/questions/47380150/dealing-with-dylibs-when-distributing-python-packages ](url)

**Comment by cabouman** [comment]
We implemented this solution, and it seems to work.
