### ISSUE TITLE
cache files

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#19]
The temp image and sino files in the cache folder should have a unique basename so that multiple instances can be run without collisions. Maybe based on a timestamp?

**Comment by bwohlberg** [comment]
It's usually a better approach to construct such unique names from the process id, which can be obtained via `os.getpid()` in Python.

**Comment by bwohlberg** [comment]
The pid approach would work for multiprocessing (at least on Unix, which uses fork for multiprocessing). Since Python multithreading is severely limited, and would not work for this application, you're pretty much stuck with multiprocessing anyway. FWIW, though, if the pid approach doesn't work, the `tempfile` module would probably be the best option.

**Comment by smajee** [comment]
Suppose we launch two processes for doing reconstruction and for both cases the system matrix is the same and it does not exist in disk yet.
Then, even if the image and sino cache files are different, both may try to write to the system matrix at the same time and that can cause issues.

What should we do in this case?

**Comment by bwohlberg** [comment]
You need to implement a file locking mechanism to lock the system matrix file on disk. You could either lock just prior to writing it to disk, or prior to starting to compute it.

**Comment by smajee** [comment]
The object_name parameter present in the recon function allows multiple instances to be run with different object_name inputs. The object_name essentially defines the filename of the cached files.

For running multi-process and multi-node reconstructions using svmbir, one needs to append the process id and hostname to the object_name before calling svmbir.recon.
This serves as a crude hook to run multi-process and multi-node reconstructions until we implement something better.
