### ISSUE TITLE
Proper setting of proximal map parameter

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#190]
I rejected the merge request because I think this feature still needs some work.

I edited the docstring, but in addition, I'm still not sure why we have the statement
`sigma_x = sigma_p`
Why are we setting sigma_x to be the same as sigma_p in the proximal map mode?

Once we agree on some of the details here, you can redo the merge request.

**Comment by dyang37** [comment]
The C code only accepts one single parameter sigma_x as the regularization term for either qGGMRF prior or proximal map prior (reconparams.SigmaX in C code). 
Therefore without changing the C code the best way I can think of to handle this is to make sigma_x and sigma_p as separate variables in python reconstruction function interface svmbir.recon(), and within the function overwrite sigma_x with sigma_p for proximal map mode, and then pass sigma_x into C code.
We can talk about this in more details either atThursday's meeting or at code review.
