### ISSUE TITLE
project/backproject do not work for single angle

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#192]
Project/backproject functions do not work for single angle, i.e. when `angles` contain only one angle.

Project function fails for a single angle since `num_views = len(angles)` cannot be assigned for scalar `angles`.

Backproject function fails for a single angle since `num_channels = sino.shape[2]` cannot be assigned since sino is 2D.

**Comment by sjkisner** [comment]
@smajee I think technically it's OK.  The specification is that `angles` is a 1D numpy array.  So if you define `angles=np.array([scalar_value])` it works.  Although it should have raised a more descriptive exception.

We could accommodate a scalar input with this check:
```
if not isinstance(angles,np.ndarray):
    angles = np.array([angles])
```
Would this be worthwhile?

**Comment by sjkisner** [comment]
The 2D sinogram is another issue. Technically the user should input a 3D numpy array.

We currently accommodate 2D sinograms for `recon()` but it assumes is that it's a single slice, not a single angle.  The test could be modified for 2D sinograms by looking at the shape of `sino` and `angles` together to determine which axis to add the singleton.

**Comment by smajee** [comment]
I didn't realize earlier that `angles=np.array([scalar_value])` works. But the check might make it more robust.

I understand the problem with interpreting the 2D sinogram now. I think it's best to leave it as it is, since the backprojection with a single angle works if one adds the singleton dimension to the sinogram.

**Comment by sjkisner** [comment]
The arguments validation needed to be updated anyway.  I added it for the next release.

You can now input a scalar angle to `backproject()`, 
and lower dimensional sinograms to `project()`.
Warnings are issued for these cases since they don't match the specifications in the docstring.
