### ISSUE TITLE
writeMatrix error

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#194]
Sometimes if I run many reconstructions (different geometry params) one after the other, I get an error with writing the system matrix. For example:
`ERROR in writeAmatrix: can't open file /nh/u/smajee/.cache/svmbir/sysmatrix/c64f94bc3105daf95650_pid25787_rndnum495.2Dsvmatrix`

Any ideas on what might be causing this?

**Comment by sjkisner** [comment]
@smajee It's a failed `fopen`.  I haven't seen this as a general problem. Could it be filling up the disk or running over a disk quota ?

**Comment by smajee** [comment]
I think you are right, I have run out of disk space. Didn't think of this possibility before. Thanks!
