### ISSUE TITLE
Discrepancy of angle range in shepp-logan demo

### ISSUE THREAD

**Issue by dyang37** [cabouman/svmbir#195]
I noticed that there's a discrepancy of angle range between the code and the comment in both 2D and 3D shepp-logan demo:

```
tilt_angle = np.pi/2 # Tilt range of +-90deg
...
# Generate array of view angles form -180 to 180 degs
angles = np.linspace(-tilt_angle, tilt_angle, num_views, endpoint=False)
```

The angle range should really be from -90 to 90 degs according to the code.

Should we correct the comment?

**Comment by sjkisner** [comment]
done
