### ISSUE TITLE
Fail to set num_threads in Lilly Cluster.

### ISSUE THREAD

**Issue by DamonLee5** [cabouman/svmbir#200]
Recently, when I am working in the mbircone repository in Lilly cluster. 
I noticed that setting num_threads in the recon function failed.

Therefore, I tested this feature of svmbir in Lilly cluster using below code. 

`for num_threads in [1,2,4,8,12,24]:`
`recon = svmbir.recon(sino, angles, T=T, p=p, sharpness=sharpness, snr_db=snr_db,num_threads=num_threads)`

> 1 Threads: Reconstruction time = 38621 ms (iterations only)
> 2 Threads: Reconstruction time = 38096 ms (iterations only)
> 4 Threads: Reconstruction time = 38458 ms (iterations only)
> 8 Threads: Reconstruction time = 38306 ms (iterations only)
> 12 Threads: Reconstruction time = 38042 ms (iterations only)
> 24 Threads: Reconstruction time = 38980 ms (iterations only)

It shows that setting num_threads in the recon function failed to change OpenMP's threads.

Currently, we set the number of threads for OpenMP by changing the environment variable.
However, there's a hierarchy of places to change for the number of threads, and the environment variable is at or near the bottom. 

The solution for this is to use OpenMP function `openmp.omp_set_num_threads(num_threads)` directly to set num_threads.
This function can be imported from OpenMP in Cython.
I implemented this in a branch of mbircone repo, please see attached link.
https://github.com/cabouman/mbircone/compare/set_threads

After this fixed,

> 1 Threads: Reconstruction time = 61837 ms (iterations only)
> 2 Threads: Reconstruction time = 32082 ms (iterations only)
> 4 Threads: Reconstruction time = 17849 ms (iterations only)
> 8 Threads: Reconstruction time = 10009 ms (iterations only)
> 12 Threads: Reconstruction time = 7179 ms (iterations only)
> 24 Threads: Reconstruction time = 4877 ms (iterations only)

**Comment by sjkisner** [comment]
The problem doesn't happen on any of my machines so I can't reproduce it, but adding the call to `omp_set_num_threads()` doesn't hurt anything.

@DamonLee5 Can you check that the version in the "set_threads" branch fixes the problem on Lilly?

**Comment by sjkisner** [comment]
Wenrui, I think you told me the same problem happened on your mac.  If that's the case could you see if the fix worked there too, and also mention the OS version?

**Comment by sjkisner** [comment]
OK, so it was running 8 threads in each of those cases. Got it.
