### ISSUE TITLE
Possible negative weight generation

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#213]
Currently, it's possible to generate and provide negative weights.

We need to implement two fixes:

1. We need to modify the "emission" option for the function `calc_weights()` so that it can't generate negative weights. This can be done with the following command:
`weights = 1 / (np.absolute(sino) + 0.1)`

2. If the weights are provided, then we need to test that they valid. This means that they either need to be NONE or they need to be strictly positive with the same shape as `sino`. To do this, we should provide a new utility in `_utils.py` with the structure 
`def weights = utils.test_args_weights(sino, weights)`
`"Test validity of weights"`

**Comment by sjkisner** [comment]
For the second point, there's already a function in _utils.py that we can modify:
`test_args_inits(init_image, prox_image, init_proj, weights, weight_type)`

**Comment by cabouman** [comment]
Good point.

**Comment by cabouman** [comment]
Fixed
