### ISSUE TITLE
Weight data type mismatch in svmbir.calc_weights

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#219]
`svmbir.calc_weights` produces weights of the same data type as `sino` for all `weight_types` except `unweighted`. For `unweighted`, the data type is always float64.  This can cause issues in some downstream applications (eg scico).

This can be fixed by doing `weights = np.ones(sino.shape).astype(sino.dtype)` for the unweighted case.

**Comment by cabouman** [comment]
Suggested fix Implemented
