### ISSUE TITLE
Add file lock to system matrix

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#22]
If multiple processes try to write the same system matrix file, there will be issues.
A file lock needs to be implemented for this.

**Comment by cabouman** [comment]
Good News! We have finally gotten to the point that this is creating problems. When doing 4D reconstructions, the different 3D processes collide.

Here is what I propose, but Jordan is the expert:
1. The C code needs to check if the system matrix file exists immediately before it writes it out.
2. If the file exists, then it should not write anything out.
3. If the file doesn't exist, it should lock the file name, and write out the file. 

What do you think?

**Comment by cabouman** [comment]
Here is pseudo-code for fix.

```
sys_matrix_file_name = Desired name of System Matrix

int =write_system_matrix( system_matrix, sys_matrix_file_name )
{
        tmp_name = cat( sys_matrix_file_name, process_id, random number );
        if(tmp_name does not exist)
                write out SystemMatrix to tmp_name;
        else {
                print("Temporary file already exists")
                return(-1);
                }

        If(sys_matrix_file_name does not exist) {
                mv tmp_name to sys_matrix_file_name;
                return(0);
                }
        else {
                rm tmp_name;
                print("System matrix file already exists")
                return(-1);
                }
}
```

**Comment by dyang37** [comment]
Bug fix in commit https://github.com/cabouman/svmbir/commit/217155cbbccb81d9852192cf8b33391f19af28b4

Ready to test.

Here's a what you'll see in std-out when no matrix file exists on disk:
```
Computing system matrix...
Writing system matrix...
C subroutine: Writing sysmatrix to file /Users/dyangsteven/.cache/svmbir/sysmatrix/7be71c6fa3b024f576ee_pid96793_rndnum296.2Dsvmatrix.
Move tmp file to location /Users/dyangsteven/.cache/svmbir/sysmatrix/7be71c6fa3b024f576ee.2Dsvmatrix
```

Here's what you'll see when a matrix file exists:
```
Computing system matrix...
Writing system matrix...
C subroutine: Writing sysmatrix to file /Users/dyangsteven/.cache/svmbir/sysmatrix/7be71c6fa3b024f576ee_pid97202_rndnum603.2Dsvmatrix.
('Found system matrix: /Users/dyangsteven/.cache/svmbir/sysmatrix/7be71c6fa3b024f576ee.2Dsvmatrix', '. Remove tmp matrix file.')
```

The std-out message `C subroutine, Writing sys matrix to file ...` is manually added in the submodule `sv-mbirct`, and is not included in the commit. To see this message please manually add the following line of code in line 699 of `src/A_comp.c`:
```
printf("C subroutine: Writing sysmatrix to file %s.\n", fname);
```

**Comment by dyang37** [comment]
Modified code as advised by @sjkisner .
Std-out when matrix file exists:
```
Found system matrix: /home/yang1467/.cache/svmbir/sysmatrix/bc0b0940eb4abd0cc86e.2Dsvmatrix
Reading system matrix...
```
std-out when matrix file does not exist:
```
Computing system matrix...
Writing system matrix...
C subroutine: Writing sysmatrix to file /home/yang1467/.cache/svmbir/sysmatrix/bc0b0940eb4abd0cc86e_pid22699_rndnum592.2Dsvmatrix.
```

**Comment by cabouman** [comment]
We added the fix by writing to a tmp file, and moving to the system file name.
