### ISSUE TITLE
Unit tests not included in manifest

### ISSUE THREAD

**Issue by bwohlberg** [cabouman/svmbir#225]
It looks as if updating this line of `MANIFEST.in`

https://github.com/cabouman/svmbir/blob/83e72b1fdf91d8193418166a4d2b10f70ed6437c/MANIFEST.in#L11

to
```
include tests/*.py
```
was overlooked when the `tests` directory was moved from within the package source directory to the repository root. As a result, the tests are not included in the source distribution.

Instead of fixing this, though, perhaps consider moving the tests back into the package source directory, which has the advantage of allowing them to be run for an installed package?

**Comment by sjkisner** [comment]
I moved the tests to the package source in PR [226](https://github.com/cabouman/svmbir/pull/226)

I think pytest.ini, MANIFEST.in  and the documentation are aligned.
