### ISSUE TITLE
Docs still refer to parallel beam geometry after generalizing geometry to include fan-beam 

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#232]
The pre-release branch contains the generalization of svmbir to include fan-beam.

However, the docs still use parallel beam terminology.

**Comment by sjkisner** [comment]
This is pretty well fixed now.  We'll probably push out another release soon. Until then you can build the updated docs locally from the `prerelease` branch.  See [here](https://svmbir.readthedocs.io/en/latest/docs.html).  If there's any comments feel free to open this issue back up.
