### ISSUE TITLE
Revised default values for fan beam geometry

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#236]
We need to change the defaults for the fan beam geometry.
The proposal is:

`delta_pixel (float, optional) – [Default=1.0] Scalar value of the spacing between image pixels in the 2D slice plane in ALU.
If geometry=parrallel, then it is automatically set to 1.0.
If geometry=fan, then it is automatically set to delta_pixel_detector/magnification.`

We might also need to modify `auto_num_rows` and `auto_num_cols` for the fan beam geometry.

**Comment by sjkisner** [comment]
Changed the default image dimensions for fan geometry in PR #237

**Comment by sjkisner** [comment]
This is done
