### ISSUE TITLE
Fan-beam projection needs to check num_channels is compatible with the input image size.

### ISSUE THREAD

**Issue by dyang37** [cabouman/svmbir#246]
This issue is spotted thanks to Surogit.
Currently, `num_channels` is used as an input to the `svmbir.project()`. 
For fan-beam geometry we might need to check that this input is compatible with the number of image columns and the geometry parameters. Without considering detector offsets, we should roughly have `num_channels*delta_channel ~= magnification*num_cols*delta_img`.
For example, in `demo_fanbeam.py, `changing `num_channels` from 256 to 128 would result in garbage reconstruction results due to mismatch between sinogram and image shapes, and this should be checked by the program.
In mbircone, this is done by first calculating the correct image shape from the sinogram and geometry parameters, and comparing it with the input image shape.

**Comment by XiaoWang-Github** [comment]
I don't understand your comment. The number of channels in the sinogram should be independent to the image reconstruction size.

**Comment by cabouman** [comment]
Diyu, I think this is not a problem for SVMBIR, but we there may be a problem with mbircone that we can set arbitrary reconstructed image sizes. That could bit use when doing laminography. But I will close this issue for SVMBIR.
