### ISSUE TITLE
Fan beam forward models

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#247]
I now have fan beam forward models for the both curved and flat detectors.  For the `geometry` argument I'm considering the following names:
```
['parallel',
'fan-curved',
'fan-flat',
'fan']   # have this default to 'fan-curved' and issue a warning
```
Any alternate suggestions?

**Comment by cabouman** [comment]
Jordan, this looks fine, but I think you can just use the first three since 'fan' is ambiguous.

**Comment by cabouman** [comment]
We added a depreciation warning for the `fan` option and mapped it to `fan-curved`. So this is done.
