### ISSUE TITLE
Change initial condition handling and defaults

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#26]

**Comment by smajee** [comment]
Set default initial condition to zero.

If initial condition is a scalar, pass only the scalar to the executable.

**Comment by cabouman** [comment]
Jordan,
I merged your pull request, but I think we still need to correct this line in the comment code used for readthedocs .
But I wanted to check with you before doing it.

Charlie

init_image (float, optional): [Default=0.0001] Initial value of reconstruction image specified by either a single scalar value or a 3D numpy array with a shape of (shape.sino[1],num_row,num_col)
=>
init_image (float, optional): [Default=0.0] Initial value of reconstruction image specified by either a single scalar value or a 3D numpy array with a shape of (shape.sino[1],num_row,num_col)

**Comment by sjkisner** [comment]
Yes I missed that.  Also found some typos there.  Should be (sino.shape[1], num_rows, num_cols) 
Change coming..

**Comment by smajee** [comment]
Perhaps we can instead say (num_slices,num_rows,num_cols) in order to be consistent with other parts of the documentation.

**Comment by sjkisner** [comment]
That's fine. I hadn't because I think "num_slices" is only used in the documentation and internally, but it's clearer nonetheless over sino.shape[1].  I'll update the pull request

**Comment by cabouman** [comment]
I think this is all done now. Thanks Jordan for getting this fixed.
