### ISSUE TITLE
Upcoming change in sharpness parameter in v0.3.0

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#260]
Starting in 0.3.0 there will be changes to the default regularization and 'sharpness' behavior (see #251 and #255).
Basically you will have to decrease the level of 'sharpness' to get the same results as svmbir-0.2

I propose we have calls to svmbir.recon print the following for 1 or 2 release cycles:
`NOTE: Default image regularization and effect of 'sharpness' parameter changed in v0.3.0.`

Would it be too noisy to do this even for quiet mode?  It's important for existing users to be aware of this.

**Comment by sjkisner** [comment]
After some discussion, an alternative is to transition these changes over 1 or 2 release cycles so results don't change abruptly without prior warning.  The implementation is in 907e093 , and the notification describes the behavior:
```
SVMBIR v0.3.0 NOTICE of pending change in regularization:
** Default image regularization and effect of 'sharpness' will change in the
** next release. To apply the changes immediately supply the following argument:
** svmbir.recon(new_reg_defaults=True,...)
```
This notice goes to stderr , and if the `new_reg_defaults` argument is applied as above the notice goes away.

**Comment by cabouman** [comment]
Yes, I like this. But we will need to add this argument to the doc string from the recon function.

**Comment by sjkisner** [comment]
The change in snr_db is being tabled for now.
