### ISSUE TITLE
Update docs to reflect changes in geometry options

### ISSUE THREAD

**Issue by bwohlberg** [cabouman/svmbir#266]
The `Overview` pages of the docs should be update to reflect the three different geometry options in `svmbir` 0.3.0.

**Comment by cabouman** [comment]
Brendt, Jordan actually updated the documentation to contain a description of the fan beam geometry. [link to the geometry documentation](https://svmbir.readthedocs.io/en/latest/overview.html) It also shows pictures of the two geometries that are supported.

Is there something you think we should add that would make this clearer?

**Comment by bwohlberg** [comment]
Sorry for not being clear. The latest version of `svmbir` supports two different fan beam geometries, but that is not reflected in the docs on readthedocs.

**Comment by sjkisner** [comment]
Documentation updated in PR #271
