### ISSUE TITLE
object_name should be optional and random by default

### ISSUE THREAD

**Issue by tbalke** [cabouman/svmbir#27]
When generating the file identification string we now allow to pass a unique sting to avoid collision when using multiple processes.

This is great but by default currently a constant string is being used ('object'). By default a random, unique string should be used, e.g. <randomNumber>, <hash(\time)> etc.

This way the advanced user can still pass a meaningful name for debugging purposes. But the general user will never need to worry about this while still not having problems with name collision.

**Comment by sjkisner** [comment]
This issue of file naming is specific to the command line interface so I think we can close it.
