### ISSUE TITLE
Sort Angles

### ISSUE THREAD

**Issue by tbalke** [cabouman/svmbir#31]
Since the code runs faster when the angles are sorted, the python code should help the user achieve the improved performance.

I suggest that the code checks before execution whether the angles are sorted.
If yes: nothing happens.
If no: show a warning, "Warning, detecting unsorted view angles which significantly lowers speed of the code. Please sort the views by angle before or set the parameter "sort_angles=True" to force sorting internally within the svmbir execution"

In the case of sort_angles, the arrays are being reorganized "behind the curtain". In the case of "recon" this happens before execution, in the case of "project" this happens before and after execution, so that the user will get the projection with the unsorted angles that they passed to the "project" routine.

Thilo

**Comment by cabouman** [comment]
I added a section to the documentation explaining this issue. After some discussion, we decided it was best not to do this within the svmbir function, and that generating a warning was perhaps unnecessary. 

In the future, we should provide a utility to users for reordering the view angles (along with the sinogram data) into a monotone increasing order in the range [0,2pi].

**Comment by cabouman** [comment]
Create utility name sino, angles = svmbir.reorder_angles(sino, angles) that reorders the angles and sinogram views to be in order on the interval [0, 2pi].

This requires two steps:
  1) angles = angles mod (2*pi) 
  2) Nindex = numpy.argsort(angles)
  3) angles = angles(Nindex)
  4) sino = sino(Nindex,:,:)

**Comment by smajee** [comment]
Should we fix the max angle to be 2*pi or should we make it variable (default being 2*pi)?
This can be useful if people want the max angle to be pi for example.

**Comment by tbalke** [comment]
I think it is overly restrictive to constrain to 2pi.

I would suggest:
Nindex = numpy.argsort(angles mod (2*pi))
angles = angles(Nindex)
sino = sino(Nindex,:,:)
weight = weight(Nindex,:,:)

This way the angles get sorted but not modified through the modulus.

Thilo

**Comment by cabouman** [comment]
We definitely don't want to restrict the angles, but I agree with Thilo that we have to remember to handle the weights. So the weights will need to be an **optional** argument in the utility. 

sino, angles, weights = svmbir.reorder_angles(sino, angles , weights=None)

Nindex = numpy.argsort(angles mod (2*pi))
angles = angles(Nindex)
sino = sino(Nindex,:,:)
weight = weight(Nindex,:,:)

**Comment by cabouman** [comment]
Responding to Greg and Diyu's comments:

1) Yes, we need to first apply the operation:
`
angle <= angle mod (2 pi)
`
so that they are all in the range of [0,2pi].

2) Great idea:  
_Try_ starting with an example with ordered angles and fast convergence, then shuffling the order to see if execution is slower, then applying your method to see if execution is back to the original.

**Comment by cabouman** [comment]
Diyu, maybe you can start a branch called "sino_sort_feature" in order to work on this new function and its documentation.

**Comment by dyang37** [comment]
Copying my comments from the email:
I agree with Thilo's algorithm except that we might not need any return variables (need to check this further with some tests).

```sino = sino(Nindex,:,:)``` wil sorts the original array, copy it to new memory address, and finally replace the previous unsorted variable. So in this case we don't need to either do ```np.copy()``` explicitly, or delete the original unsorted array to save memory space.

We can double check that we are indeed copying a sorted array (let's say ```sino```) to a new memory address by calling ```id(sino)``` before and after the function call, and make sure that they are different.

**Comment by dyang37** [comment]
Sure will do.
________________________________

**Comment by dyang37** [comment]
PR submitted.

**Comment by sjkisner** [comment]
These the results I got from the demo. 
Using gcc:
> Processing time for original:  97.33023023499999 s
> Processing time for shuffled:  160.626099447 s
> Processing time for sorted:  99.38434820099997 s

Using icc:
> Processing time for original:  82.84277675 s
> Processing time for shuffled:  119.41927515600001 s
> Processing time for sorted:  83.04920080400001 s

**Comment by sjkisner** [comment]
See [pull/198](https://github.com/cabouman/svmbir/pull/198) for a couple code comments

**Comment by sjkisner** [comment]
Seems to work. I posted these on the closed pull request thread, so adding here:

1. The demo.zip file added with this feature contains image output and the \_\_pycache\_\_ folder, which I think was a mistake. It's a lot larger than it need to be.
2. In the demo there's a figure that's saved after the user is instructed to close it, so the file output/angle_orders.png is a blank image.

**Comment by cabouman** [comment]
I think we have address all the concerns in this issue with the addition of the sino_sort() function and demo.
