### ISSUE TITLE
calloc error

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#43]
Alejandro is getting a ``get_spc calloc()`` error when running a reconstruction with a sinogram with 980 channels 225 views and 2 slices. I have test data, but I'm not attaching it because it is 1.8Mbytes, but I can email it to anyone who needs it.

**Comment by sjkisner** [comment]
Also add Alejandro's error is occurring on a Windows machine.

I ran Alejandro's test data and script on Linux and Windows machines and didn't have a problem.

**Comment by sjkisner** [comment]
Closing this because it's not a coding issue.  The problem came from using a 32-bit compiler which didn't provide enough addressable memory.  Probably a common issue because the standard MinGW/gcc compiler is 32-bit (!!)
