### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#45]
We need to integrate unit tests into our package. These tests can be used to automatically test code when a pull request is done. 

Perhaps we can generate a python utility that that generates synthetic sinogram data. For example, using the Shepp-Logan phantom is specified at https://en.wikipedia.org/wiki/Shepp–Logan_phantom . So a python utility can be created that generates a 3D phantom by rotating a conical section of the Shepp-Logan.

Also, we should use the ``pytest`` package for implementing the unit tests.
We might also need to use something called ``travis``.

**Comment by cabouman** [comment]
Wenrui, I took a look at your test code, and you have made great progress. Here are a few comments.

1) **Center offset:** I notice that you have set ``center_offset=-6`` in your tests. I'm not sure why you would do this. If you just do nothing, then it will default to ``center_offset=0``, which is the simplest and most obvious case to test. I would use the default value of ``center_offset`` in all the tests you currently have. (Later we can generate additional tests that test unusual parameter settings.)

2) **Rename the tests:** Your test names are things like ``test_01`` and ``test_02``. You should give your tests names that are understandable like ``2D_recon_test`` and ``3D_recon_test``.

3) **Rename phantom generator:** I would change the name of ``generate_2D_phantom(img_size)`` to something like ``svmbir.gen_3D_SL_phantom(num_rows,num_cols)``. This will allow for the generation of other phantom types in the future.

4) **Non-rectangular images:** You need to do a 3D test with a limited angle and a non-rectangular image. I suggest you modify your image generation routines so that the input is ``num_rows``, ``num_cols``, and ``num_slices``. Then one of your examples should use ``num_rows=256``, ``num_cols=128``, and ``num_slices=8`` with ``angles`` ranging between -2*pi/3 and 2*pi/3 . This is typical of a TEM tilt series.

5) **Possibly tighter thresholds:** I'm not sure if your test threshold of 0.005 is tight enough. You should find out what values are generated for say line 62, and then set the threshold be maybe 2x the observed value so the test will be sensitive to any problem with convergence.

**Comment by DamonLee5** [comment]
Got it. I will update it this morning. I think I may have some
problems in *Non-rectangular
images. *If I do meet some problem, I will ask questions through email.

Best,
Wenrui

**Comment by cabouman** [comment]
OK, I suggest you scale the phantom based on the smallest dimension, i.e., min(num_rows, num_cols); and you center the phantom along both axises of the image. That should be good enough for now.

**Comment by DamonLee5** [comment]
Rename the tests: 'test_' is Keywords in pytest. I will make it test_2D_recon and test_3D_recon.

**Comment by DamonLee5** [comment]
# Parameters
num_rows=128, num_cols=256, num_views=144, with angles ranging between -pi/3 and pi/3.

# Ground Truth
![image_test01](https://user-images.githubusercontent.com/22163570/98704736-fd59b980-234a-11eb-9a40-bb603059d5f9.png)

# Recon
![recon_test01](https://user-images.githubusercontent.com/22163570/98704733-fcc12300-234a-11eb-8857-f3fb4f64c89e.png)

**Comment by DamonLee5** [comment]
# Parameters
num_rows=256, num_cols=128, num_views=144, with angles ranging between -pi/3 and pi/3.

# Ground Truth
![image_test01](https://user-images.githubusercontent.com/22163570/98725481-29813480-2363-11eb-826e-d2cc754ea09a.png)

# Full view
![recon_test01](https://user-images.githubusercontent.com/22163570/98725714-7e24af80-2363-11eb-8aee-6ac9b7843e3e.png)

# Limited view
![recon_test01](https://user-images.githubusercontent.com/22163570/98725791-9ac0e780-2363-11eb-8396-5d87aa1b76ab.png)

**Comment by DamonLee5** [comment]
# Parameters
num_rows=256, num_cols=128, num_views=144, with angles ranging between -pi/3 and pi/3.

# Generated 3D Slice  Microscopy Sample
![image_test03](https://user-images.githubusercontent.com/22163570/98863555-8a2d7180-2436-11eb-9ed8-20d67d62bc3a.png)

# Sinogram 
![sino_test03](https://user-images.githubusercontent.com/22163570/98863574-91547f80-2436-11eb-882d-26264c7efeec.png)

# Recon
![recon_test03](https://user-images.githubusercontent.com/22163570/98863586-96193380-2436-11eb-9325-21e7aca3e26b.png)

**Comment by cabouman** [comment]
Yes, this is good.

**Comment by DamonLee5** [comment]
# The shepp logan phantom.
![sl_phantom](https://user-images.githubusercontent.com/22163570/99029037-6d309580-253f-11eb-89e1-27f9ff824c54.png)

**Comment by cabouman** [comment]
We have completed an initial implementation of unit tests. More will need to be done later.
