### ISSUE TITLE
Github Citation

### ISSUE THREAD

**Issue by XiaoWang-Github** [cabouman/svmbir#48]
Is there a way that I can cite this github project in papers?

**Comment by cabouman** [comment]
I'm not sure if there is a specific protocol for citing a GitHub project. I think you can just cite the URL.

**Comment by bwohlberg** [comment]
My recommendation would be to put it in your bibtex file as a Misc entry, as
```
@Misc {cite-key,
  author =	 {Author Names},
  title =	 {{S}uper-{V}oxel {M}odel {B}ased {I}terative {R}econstruction ({SVMBIR})},
  howpublished = {Software library available from \url{https://github.com/cabouman/svmbir}},
  year =	 2020
}
```
and then cite it in the docs using :cite:\`cite-key\`. Some people go to the effort of registering a snapshot of the project with [Zenodo](https://zenodo.org/) to get a doi. Another option would be to present a paper on the project at SciPy.

**Comment by XiaoWang-Github** [comment]
Sounds good. Thank you!

**Comment by sjkisner** [comment]
I started the process of generating DOIs for the sv-mbirct package but I decided I didn't like the idea of links hanging around that point to surely outdated version of the code.

**Comment by cabouman** [comment]
In the mean time, is there a standard way of posting the bibtex citation for people to use? 
Should be put it in the document? Maybe in the overview section?

**Comment by bwohlberg** [comment]
I'm not aware of a standard way of handling this. My suggestion would be to put a reference in the overview section of the docs.
