### ISSUE TITLE
Limited 2D slice reconstruction

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#53]
We should implement the code:

	if sino.ndim == 2: 
		sino = sino[:,np.newaxis,:]
		print("warning: Input sino array only 2D. Adding singleton dimension to slice index to make it 3D.

When we implement proper error handling, we can roll this up into it. This would cause the code to run “properly” even when the user provides a 2D input, but it doesn’t required that we redo everything. In practice, this is useful because people might routinely want to reconstruct single slices without reconstructing a full volume.

**Comment by sjkisner** [comment]
I added this mostly as written above.
There's a standard `warnings` library that may be preferable to use, but I'll punt that until we introduce Exceptions and Warnings more widely in the package.
