### ISSUE TITLE
Change defaults for stopping criteria

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#55]
Jordan will investigate the use of stopping parameters given by

``stop_threshold`` = 0.05
``max_iterations`` = 100

Once Jordan confirms that these values work for a wide range of cases, we will implement them as the ``svmbir`` defaults.

**Comment by cabouman** [comment]
After some experimentation, I'm leaning towards stopping parameters given by:

``stop_threshold`` = 0.005
``max_iterations`` = 40

Please give feedback.

**Comment by sjkisner** [comment]
These settings are probably OK.  `stop_threshold=0.005` % is very small so I think for a lot of problems it will hit 40 iterations first.

We should highlight the `max_iterations` setting because for some applications 40 won't be enough, and it might not be obvious that the poor output is because it's not converged.

**Comment by cabouman** [comment]
Is out better to default to?

``stop_threshold = 0.01``
``max_iterations = 100``

**Comment by sjkisner** [comment]
Yes that's probably better.  There won't be an optimal setting for all situations..we don't want it to run excessively long when it isn't necessary. This looks like a good middle.  How about just doing this and we can adjust if it's obvious we should change it.

I still think we should mention that convergence will be slower for highly regularized settings, and for limited angle cases, so the max_iterations may need to be increased if the image looks bad.  We could also mention that visible square patterns also means it's not converged.

**Comment by cabouman** [comment]
Jordan, I've been playing around with the microscopy phantom, and I totally understand what you mean. I think the microscopy geometry would really benefit from the multiresolution reconstruction.
