### ISSUE TITLE
Add proximal map mode

### ISSUE THREAD

**Issue by smajee** [cabouman/svmbir#6]

**Comment by youxia512** [comment]
Do you mean consensus equilibrium?  If that's what you meant, Venkatesh has a super-voxel code that has a consensus equilibrium mode.

**Comment by smajee** [comment]
The svmbir is meant to be a wrapper around the sv-mbirct  code that people can use to run reconstructions in python.

To that end, I want the svmbir code to do only a few simple things (recon with MRF prior, recon with proximal map and forward project) really well in order to appeal to a wide variety of people and be easy to maintain.

I believe performing reconstruction using PnP or MACE is out of the scope of this repository, but I want to build-in the hooks (recon with proximal map) that will enable someone to implement MACE/PnP reconstruction using the hooks in the svmbir package.



On Sep 11, 2020, at 11:17 PM, Xiao Wang <notifications@github.com<mailto:notifications@github.com>> wrote:



Do you mean consensus equilibrium? If that's what you meant, Venkatesh has a super-voxel code that has a consensus equilibrium mode.

**Comment by cabouman** [comment]
We should discuss our strategy on this. It would be really good if we could provide some kind of wrapper that implemented a basic PnP or CE.

**Comment by youxia512** [comment]
Hi Soumendu and Professor Bouman,  I think Venkatesh has left a hook for the PnP framework in the open source baseline code, bu t not the SV code. I think that's what he told me this summer. Do you think that you can copy what he wrote in the baseline code to the SV code?

**Comment by smajee** [comment]
I believe the sv-mbirct code also has hooks for proximal maps.
I just have to change the python wrapper to access those hooks that are in the c code.
It should be relatively straight-forward, I just have to find some time for it.

**Comment by cabouman** [comment]
Issue fixed by new interface.
