### ISSUE TITLE
Memory bug

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#77]
Venkat is having a problem with a malloc error. See program failure below.

Warning in /home/.cache/svmbir/parbeam/par/object.reconparams: InitImageValue should be positive. Reverting to default.
RECONSTRUCTION/PRIOR PARAMETERS:
- Prior Type                                            = QGGMRF
- Q-GGMRF Prior Parameter, q                            = 1.200000
- Q-GGMRF Prior Parameter, p                            = 2.000000
- Q-GGMRF Prior Parameter, T                            = 0.001000
- Prior Regularization parameter, SigmaX                = 0.3500000 (mm^-1)
- Scaling for sino weights, SigmaY (W=exp(-y)/SigmaY^2) = 0.0106114 (mm^-1)
- Prior weight for nearest neighbors within slice       = 0.1132759
- Prior weight for diagonal neighbors within slice      = 0.0800861
- Prior weight for nearest neighbors in adjacent slices = 0.1132759
- Inital image value                                    = 0.020253   (mm-1)
- Stop threshold for convergence                        = 0.1000000 %
- Maximum number of ICD iterations                      = 25
- Positivity constraint flag                            = 0

Reading system matrix...
==> malloc() error
Traceback (most recent call last):
 File "compareMBIR.py", line 94, in <module>
   rec_mbir_sv = np.float32(svmbir.recon(proj,theta, weights=wt_data/wt_data.mean(), num_threads=40,center_offset=0, max_iterations=25,positivity=False,stop_threshold=stop_thresh,roi_radius=1024,sigma_x = MRF_SIGMA, T = 0.001))
 File "/home/svmbir/svmbir/svmbir.py", line 454, in recon
   imgparams['Nx'], imgparams['Ny'], imgparams['Nz'])
 File "/home/svmbir/svmbir/_utils.py", line 144, in read_recon_openmbir
   with open(fname, 'rb') as fileID:
FileNotFoundError: [Errno 2] No such file or directory: '/home/.cache/svmbir/parbeam/recon/object_slice0000.2Dimgdata’

**Comment by sjkisner** [comment]
Ima close this because I believe the bug was already fixed. The error tells me the version of the C-code is prior to fixing the overflow problem in allocate.c back in August.
